# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python: 3.5

install: pip install -r requirements.txt --use-mirrors

script: python setup.py test

